server:
  port: 8080

#spring:
#  application:
#    name: SpringBootDemo1
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        cluster-name: SH
##        namespace: 1a1d1570-3a62-44d4-8351-6635b8d246c9
#    loadbalancer:
#      nacos:
#        enabled: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8085/eureka/